[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
drop_bomb = "0.1.5"
lexer = { path = "../lexer" }
rowan = "0.15.15"
syntax = { path = "../syntax" }

[dev-dependencies]
expect-test = "1.5.0"
